<div class="container">
  <div class="starter-template">
    <h1>Reports</h1>
    <p class="lead">Following is a list of product reports that need to be handled.</p>
    <table class="table table-bordered table-striped">
      <thead>
	<tr>
	  <th>Barcode</th>
	  <th>Name</th>
	  <th>Company</th>
	  <th>Vegan</th>
	  <th>Comment</th>
	  <th>Action</th>
	</tr>
      </thead>
      <tbody>
	<?php echo $this->reports ?>
      </tbody>
    </table>
  </div>
</div>